from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard_admin, name='dashboard_admin'),
    path('inventario/', views.inventario_admin, name='inventario_admin'),
    # CRUD Reactivos
    path('reactivos/', views.reactivos_admin, name='reactivos_admin'),
    path('inventario/quimico/agregar/', views.agregar_quimico_admin, name='agregar_quimico_admin'),
    path('inventario/quimico/<int:quimico_id>/editar/', views.editar_quimico_admin, name='editar_quimico_admin'),
    path('inventario/quimico/<int:quimico_id>/eliminar/', views.eliminar_quimico_admin, name='eliminar_quimico_admin'),
    # CRUD Materiales
    path('materiales/', views.materiales_admin, name='materiales_admin'),
    path('inventario/material/agregar/', views.agregar_material_admin, name='agregar_material_admin'),
    path('inventario/material/<int:material_id>/editar/', views.editar_material_admin, name='editar_material_admin'),
    path('inventario/material/<int:material_id>/eliminar/', views.eliminar_material_admin, name='eliminar_material_admin'),
    # CRUD Equipos
    path('equipos/', views.equipos_admin, name='equipos_admin'),
    path('inventario/equipo/agregar/', views.agregar_equipo_admin, name='agregar_equipo_admin'),
    path('inventario/equipo/<int:equipo_id>/editar/', views.editar_equipo_admin, name='editar_equipo_admin'),
    path('inventario/equipo/<int:equipo_id>/eliminar/', views.eliminar_equipo_admin, name='eliminar_equipo_admin'),
    # CRUD Estudiantes
    path('estudiantes/', views.estudiantes_admin, name='estudiantes_admin'),
    path('estudiantes/agregar/', views.agregar_estudiante_admin, name='agregar_estudiante_admin'),
    path('estudiantes/<int:estudiante_id>/editar/', views.editar_estudiante_admin, name='editar_estudiante_admin'),
    path('estudiantes/<int:estudiante_id>/eliminar/', views.eliminar_estudiante_admin, name='eliminar_estudiante_admin'),
    # CRUD Guías
    path('guias/', views.guias_admin, name='guias_admin'),
    path('guias/agregar/', views.agregar_guia_admin, name='agregar_guia_admin'),
    path('guias/<int:guia_id>/editar/', views.editar_guia_admin, name='editar_guia_admin'),
    path('guias/<int:guia_id>/eliminar/', views.eliminar_guia_admin, name='eliminar_guia_admin'),
    path('guias/eliminar/<int:guia_id>/', views.eliminar_guia_admin, name='eliminar_guia_admin'),
    # CRUD Jornadas
    path('jornadas/', views.jornadas_admin, name='jornadas_admin'),
    path('jornadas/agregar/', views.agregar_jornada_admin, name='agregar_jornada_admin'),
    path('jornadas/<int:jornada_id>/editar/', views.editar_jornada_admin, name='editar_jornada_admin'),
    path('jornadas/<int:jornada_id>/eliminar/', views.eliminar_jornada_admin, name='eliminar_jornada_admin'),
    # CRUD Salones
    path('salones/', views.salones_admin, name='salones_admin'),
    path('salones/agregar/', views.agregar_salon_admin, name='agregar_salon_admin'),
    path('salones/<int:salon_id>/editar/', views.editar_salon_admin, name='editar_salon_admin'),
    path('salones/<int:salon_id>/eliminar/', views.eliminar_salon_admin, name='eliminar_salon_admin'),
    # CRUD Profesores
    path('profesores/', views.profesores_admin, name='profesores_admin'),
    path('registrar-profesor/', views.registrar_profesor, name='registrar_profesor'),
    path('profesores/editar/<int:profesor_id>/', views.editar_profesor, name='editar_profesor'),
    path('profesores/eliminar/<int:profesor_id>/', views.eliminar_profesor, name='eliminar_profesor'),
    path('perfil/', views.perfil_admin, name='perfil_admin'),
]
