# Generated by Django 5.2.6 on 2025-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuadernoentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
