# Generated by Django 4.2.24 on 2025-09-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0010_guia_salones'),
        ('core', '0004_quimico_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadernoentry',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='profesor.guia'),
        ),
    ]
