# Generated by Django 4.2.24 on 2025-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_equipo_material_quimico_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadernoentry',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
