# Generated by Django 4.2.24 on 2025-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cuadernoentry_retroalimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ficha_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='fichas/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='protocolo_uso',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='ficha_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='fichas/'),
        ),
        migrations.AddField(
            model_name='material',
            name='protocolo_uso',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
        migrations.AddField(
            model_name='quimico',
            name='ficha_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='fichas/'),
        ),
        migrations.AddField(
            model_name='quimico',
            name='protocolo_uso',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
    ]
