# Generated by Django 4.2.23 on 2025-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipo_ficha_seguridad_equipo_protocolo_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/'),
        ),
    ]
