# Generated by Django 4.2.23 on 2025-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadernoentry',
            name='quimico',
        ),
        migrations.AddField(
            model_name='cuadernoentry',
            name='quimicos',
            field=models.ManyToManyField(to='core.quimico'),
        ),
    ]
