# Generated by Django 4.2.23 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cuadernoentry_quimico_cuadernoentry_quimicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='cas',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
