# Generated by Django 4.2.25 on 2025-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quimico_cas'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='codigo_inventario',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
