# Generated by Django 4.2.25 on 2025-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quimico_codigo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimico',
            name='codigo_inventario',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
