# Generated by Django 4.2.25 on 2025-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_quimico_codigo_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadernoentry',
            name='imagen',
        ),
        migrations.AddField(
            model_name='cuadernoentry',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cuadernos/'),
        ),
    ]
