# Generated by Django 4.2.24 on 2025-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jornada',
            name='salones',
            field=models.ManyToManyField(blank=True, related_name='jornadas', to='profesor.salon'),
        ),
    ]
