# Generated by Django 4.2.24 on 2025-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
