# Generated by Django 4.2.24 on 2025-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0004_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('EXT', 'Extranjero')], default='CC', max_length=4),
        ),
    ]
