# Generated by Django 4.2.24 on 2025-09-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0005_estudiante_nombre_estudiante_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
    ]
