# Generated by Django 4.2.24 on 2025-09-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0006_remove_estudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='profesor.jornada'),
        ),
    ]
