# Generated by Django 4.2.24 on 2025-09-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0007_estudiante_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
