# Generated by Django 4.2.24 on 2025-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0009_estudiante_contacto_emergencia_estudiante_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='salones',
            field=models.ManyToManyField(blank=True, related_name='guias_asignadas', to='profesor.salon'),
        ),
    ]
