# Generated by Django 4.2.23 on 2025-10-01 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profesor', '0010_guia_salones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='profesor',
        ),
        migrations.AddField(
            model_name='jornada',
            name='profesores',
            field=models.ManyToManyField(related_name='jornadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
