# Generated by Django 4.2.24 on 2025-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
