# Generated by Django 4.2.25 on 2025-12-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
